version: "1.0"
stages:
  - clone
  - test
  - deploy

steps:
  clone:
    title: Cloning repository
    type: git-clone
    repo: philzona/k8s-wordsmith-demo
    revision: ${{CF_BRANCH}}
    git: github-cf
    stage: clone

  deploy:
    type: helm
    arguments:
      action: push
      chart_name: /codefresh/volume/k8s-wordsmith-demo/charts/wordsmith
      chart_repo_url: 'cm://h.cfcr.io/philzona/default'
    stage: deploy