version: "1.0"
stages:
  - clone
  - build

steps:
  clone:
    title: Cloning repository
    type: git-clone
    repo: philzona/k8s-wordsmith-demo
    revision: ${{CF_BRANCH}}
    git: github
    stage: clone

  build:
    title: Building Docker image
    type: build
    image_name: codefresh-phil/wordsmith-words
    working_directory: ${{clone}}/words
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}"
    dockerfile: Dockerfile
    stage: build
    on_success:
      metadata:
        set:
          - ${{build.imageId}}:
            - build_passed: true
    on_fail:
      metadata:
        set:
          - ${{build.imageId}}:
            - build_passed: false